name: Build Win64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg
        uses: lukka/run-vcpkg@v10

      - name: Run CMake consuming vcpkg.json by mean of vcpkg.
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "win64-2019"
          buildPreset: "win64-2019-rel"
